### ISSUE TITLE
Speed (C) False Flag

### ISSUE THREAD

**Issue by coolpvpv** [SquareCodeFX/SuicideProject#1]
How you trigger the false positive

Get diamond boots enchant them with depth strider 3 then go in water it will false Speed (C)

Anticheat Version: Latest
Server Version: 1.8.8
ProtocolLib Version: Latest

**Comment by EinWildesPanda** [comment]
Will be fixed in the next update (gonna work on it this afternoon)

**Comment by EinWildesPanda** [comment]
Fixed.
