### ISSUE TITLE
Kickt for Hacking

### ISSUE THREAD

**Issue by MysNigel** [SquareCodeFX/SuicideProject#2]
I was kickt for hacking when i was lagging.
My friend have the same issue.

Pls help and fix this bug

**Comment by MysNigel** [comment]
Btw now im banned

**Comment by EinWildesPanda** [comment]
I assume, that you weren't kicked with the message "Are you (or the server) lagging badly?" So the pingspoof check will be changed, that it can't flag anymore, but disables all the ping checks for the player (if failed)

**Comment by EinWildesPanda** [comment]
Fixed.
